### PR TITLE
organisation + formatting

### PR DESCRIPTION
**Pull request by Rcsuax**

### CODE REVIEW

**Comment by ElMuchoLoco** [comment]
Thanks Bish

    On Friday, 22 April 2022, 23:37:27 BST, Rcsuax ***@***.***> wrote:  
 
 
You can view, comment on, or merge this pull request online at:

  https://github.com/ElMuchoLoco/Zefix-Extract/pull/1

Commit Summary
   
   - b85dee9 format

File Changes 
 
(47 files)
   
   -  D CHE-102.978.503/1004487346.pdf (0) 
   -  D CHE-102.978.503/1004527311.pdf (0) 
   -  D CHE-102.978.503/1004601698.pdf (0) 
   -  D CHE-102.978.503/1004690135.pdf (0) 
   -  D CHE-102.978.503/1004793215.pdf (0) 
   -  D CHE-102.978.503/1004861132.pdf (0) 
   -  D CHE-102.978.503/1004962081.pdf (0) 
   -  D CHE-102.978.503/1004971517.pdf (0) 
   -  D CHE-102.978.503/1005086678.pdf (0) 
   -  D CHE-102.978.503/1005141854.pdf (0) 
   -  D CHE-102.978.503/1005270277.pdf (0) 
   -  D CHE-102.978.503/1005324717.pdf (0) 
   -  D CHE-102.978.503/1005373551.pdf (0) 
   -  D CHE-102.978.503/2396417.pdf (0) 
   -  D CHE-102.978.503/2404441.pdf (0) 
   -  D CHE-102.978.503/3301077.pdf (0) 
   -  D CHE-102.978.503/3354687.pdf (0) 
   -  D CHE-102.978.503/3707235.pdf (0) 
   -  D CHE-102.978.503/4007477.pdf (0) 
   -  D CHE-102.978.503/4043885.pdf (0) 
   -  D CHE-102.978.503/6451646.pdf (0) 
   -  D CHE-102.978.503/6750894.pdf (0) 
   -  D Discard/zefix_extract.py (71) 
   -  D Discard/zefix_extract_retired.py (71) 
   -  D __pycache__/zefix_extract.cpython-38.pyc (0) 
   -  D __pycache__/zefix_extract_selenium.cpython-38.pyc (0) 
   -  A config/data.json (5) 
   -  A config/events_and_comments.json (62) 
   -  A config/file_attachments.json (69) 
   -  A config/list_of_entities.json (5) 
   -  A config/significant_persons.json (138) 
   -  A config/timeline_data.json (300) 
   -  D data.json (1) 
   -  D events_and_comments.json (1) 
   -  D file_attachments.json (1) 
   -  D geckodriver.log (753) 
   -  R libs/chromedriver.exe (0) 
   -  R libs/geckodriver.exe (0) 
   -  D list_of_entities.json (1) 
   -  D significant_persons.json (1) 
   -  R src/driver.py (2) 
   -  R src/urls.py (0) 
   -  R src/zefix_extract_selenium.py (0) 
   -  D timeline_data.json (1) 
   -  D webserver.py (9) 
   -  D zefix_profile_parser.py (0) 
   -  D zefix_scrape.py (0) 

Patch Links:
   
   - https://github.com/ElMuchoLoco/Zefix-Extract/pull/1.patch
   - https://github.com/ElMuchoLoco/Zefix-Extract/pull/1.diff

**Comment by ElMuchoLoco** [comment]
What do you think of having all these selectors in the driver.py, i'm not sure whether I like that structure or whether to throw the files in different .py files and subdirectories hmm

    On Saturday, 23 April 2022, 00:24:22 BST, Matt X ***@***.***> wrote:  
 
  Thanks Bish

    On Friday, 22 April 2022, 23:37:27 BST, Rcsuax ***@***.***> wrote:  
 
 
You can view, comment on, or merge this pull request online at:

  https://github.com/ElMuchoLoco/Zefix-Extract/pull/1

Commit Summary
   
   - b85dee9 format

File Changes 
 
(47 files)
   
   -  D CHE-102.978.503/1004487346.pdf (0) 
   -  D CHE-102.978.503/1004527311.pdf (0) 
   -  D CHE-102.978.503/1004601698.pdf (0) 
   -  D CHE-102.978.503/1004690135.pdf (0) 
   -  D CHE-102.978.503/1004793215.pdf (0) 
   -  D CHE-102.978.503/1004861132.pdf (0) 
   -  D CHE-102.978.503/1004962081.pdf (0) 
   -  D CHE-102.978.503/1004971517.pdf (0) 
   -  D CHE-102.978.503/1005086678.pdf (0) 
   -  D CHE-102.978.503/1005141854.pdf (0) 
   -  D CHE-102.978.503/1005270277.pdf (0) 
   -  D CHE-102.978.503/1005324717.pdf (0) 
   -  D CHE-102.978.503/1005373551.pdf (0) 
   -  D CHE-102.978.503/2396417.pdf (0) 
   -  D CHE-102.978.503/2404441.pdf (0) 
   -  D CHE-102.978.503/3301077.pdf (0) 
   -  D CHE-102.978.503/3354687.pdf (0) 
   -  D CHE-102.978.503/3707235.pdf (0) 
   -  D CHE-102.978.503/4007477.pdf (0) 
   -  D CHE-102.978.503/4043885.pdf (0) 
   -  D CHE-102.978.503/6451646.pdf (0) 
   -  D CHE-102.978.503/6750894.pdf (0) 
   -  D Discard/zefix_extract.py (71) 
   -  D Discard/zefix_extract_retired.py (71) 
   -  D __pycache__/zefix_extract.cpython-38.pyc (0) 
   -  D __pycache__/zefix_extract_selenium.cpython-38.pyc (0) 
   -  A config/data.json (5) 
   -  A config/events_and_comments.json (62) 
   -  A config/file_attachments.json (69) 
   -  A config/list_of_entities.json (5) 
   -  A config/significant_persons.json (138) 
   -  A config/timeline_data.json (300) 
   -  D data.json (1) 
   -  D events_and_comments.json (1) 
   -  D file_attachments.json (1) 
   -  D geckodriver.log (753) 
   -  R libs/chromedriver.exe (0) 
   -  R libs/geckodriver.exe (0) 
   -  D list_of_entities.json (1) 
   -  D significant_persons.json (1) 
   -  R src/driver.py (2) 
   -  R src/urls.py (0) 
   -  R src/zefix_extract_selenium.py (0) 
   -  D timeline_data.json (1) 
   -  D webserver.py (9) 
   -  D zefix_profile_parser.py (0) 
   -  D zefix_scrape.py (0) 

Patch Links:
   
   - https://github.com/ElMuchoLoco/Zefix-Extract/pull/1.patch
   - https://github.com/ElMuchoLoco/Zefix-Extract/pull/1.diff

**Comment by Rcsuax** [comment]
> What do you think of having all these selectors in the driver.py, i'm not sure whether I like that structure or whether to throw the files in different .py files and subdirectories hmm 

do you mean in zefix_extract_selenium.py? there are no selectors in drivers.py

keep the selectors. they are constants why make another developer have to look in multiples for them when they should stay with the relevant bit of code

no need to make sub directories for no reason, keep everything in one script / place unless you have some reasoning for it to be otherwise

**Comment by ElMuchoLoco** [comment]
Haha uh oooooohhh, i've made changes

    On Saturday, 23 April 2022, 11:08:51 BST, Rcsuax ***@***.***> wrote:  
 
 



What do you think of having all these selectors in the driver.py, i'm not sure whether I like that structure or whether to throw the files in different .py files and subdirectories hmm


do you mean in zefix_extract_selenium.py? there are no selectors in drivers.py

keep the selectors. they are constants why make another developer have to look in multiples for them when they should stay with the relevant bit of code

no need to make sub directories for no reason, keep everything in one script / place unless you have some reasoning for it to be otherwise

**Pull request closed without merging**
